---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 4.5.1
repos:
  # use pre-commit from inside uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.26
    hooks:
      - id: uv-lock
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: check-case-conflict

  # check the toml file is correctly formatted
  - repo: https://github.com/brody4hire/pretty-toml-sort
    rev: toml-pretty-sort-0.0.3
    hooks:
      - id: pretty-toml-sort
        args: ["--trailing-comma-inline-array"]
        files: ^pyproject\.toml$
  # validate the toml file is valid
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
        files: ^pyproject\.toml$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.11
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format

  # you must do pip install deptry
  - repo: local
    hooks:
      - id: deptry
        name: deptry
        entry: uv run deptry .
        language: system
        pass_filenames: false
        always_run: true


  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        name: markdownlint
        language: ruby
        types: [markdown]
        entry: mdl
        stages: [pre-commit]

  # check for spelling errors
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: codespell
        language: python
        types_or: [python, markdown]
        entry: codespell
        stages: [pre-commit]
  # check for spelling errors
  - repo: https://github.com/crate-ci/typos
    rev: v1.42.1
    hooks:
      - id: typos

  - repo: https://github.com/FHPythonUtils/LicenseCheck
    rev: "2025.1.0"
    hooks:
      - id: licensecheck
        types: [python]
