---
# for days:
# Monday=0,Tuesday=1,Wednesday=2,Thursday=3,Friday=4,Saturday=5,Sunday=6
# for weeks, occurance N in month:
# First=1, Second=2
events:
# Sunday
  sundaymorning:
    days:
      - 6
    weeks:
    disabled: False
    desc: "<p>Parish Holy Communion Service from the Book of Common Worship.</p>"
    title: "Parish Communion (morning)"
    starttime: "10:00:00"
    endtime: "11:15:00"
    tags:
      - communion
      - bcp
      - service
      - morning
      - worship
      - hymns
      - organ
    categories:
      - communion
      - worship
    image: 963
  evensong:
    days:
      - 6
    weeks:
      - 1
      - 4
    disabled: False
    desc: "<p>Evening service of Evensong</p>"
    title: "A service of Evensong (evening)"
    starttime: "18:30:00"
    endtime: "19:45:00"
    tags:
      - bcp
      - evensong
      - evening
      - service
      - worship
    categories:
      - worship
      - evensong
    image: 1010
  taize:
    days:
      - 6
    weeks:
      - 3
    disabled: False
    desc: >
          <h1>A Taiz&eacute; or Iona Celtic worship service</h1>
          <p>A Taiz&eacute; or Iona Celtic worship service involves sung and chanted prayers, meditations, a period of
          silence, liturgical readings, and icons.</p>
    excerpt: >
             <p>A Taiz&eacute; or Iona Celtic worship service involves sung and chanted prayers, meditations, a period
             of silence, liturgical readings, and icons.</p>
    title: "Taiz&eacute; or Iona Celtic Service (evening)"
    starttime: "18:30:00"
    endtime: "19:30:00"
    tags:
      - evening
      - service
      - worship
      - taize
      - iona
      - chanting
    categories:
      - worship
    image: 1148
  choralevensong:
    days:
      - 6
    weeks:
      - 2
    disabled: False
    desc: "<p>Evening service of Choral Evensong</p>"
    title: "A service of Choral Evensong (evening)"
    starttime: "18:30:00"
    endtime: "19:45:00"
    skipmonths:
      - 8
    tags:
      - bcp
      - evensong
      - evening
      - service
      - choir
      - choralevensong
      - worship
      - hymns
      - organ
    categories:
      - worship
      - choralevensong
      - evensong
    image: 1010
  evensongsummer:
    days:
      - 6
    weeks:
      - 1
      - 2
      - 3
      - 4
      - 5
    disabled: False
    desc: "<p>Evening service of Evensong</p>"
    title: "A service of Evensong (evening)"
    starttime: "18:30:00"
    endtime: "19:45:00"
    skipmonths:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 9
      - 10
      - 11
      - 12
    tags:
      - bcp
      - evensong
      - evening
      - service
      - worship
    categories:
      - worship
      - evensong
    image: 1010
  4oclock:
    days:
      - 6
    weeks:
      - 1
    disabled: False
    desc: >
          <h1>4 O&#8217;clock Church</h1>
          <p><img decoding="async" class="aligncenter wp-image-957 size-full"
          src="/wp-content/uploads/2026/01/4oclock-e1768496522387.jpg" alt="" width="1067" height="1453"
          srcset="/wp-content/uploads/2026/01/4oclock-e1768496522387.jpg 1067w,
          /wp-content/uploads/2026/01/4oclock-e1768496522387-220x300.jpg 220w,
          /wp-content/uploads/2026/01/4oclock-e1768496522387-752x1024.jpg 752w,
          /wp-content/uploads/2026/01/4oclock-e1768496522387-768x1046.jpg 768w,
          /wp-content/uploads/2026/01/4oclock-e1768496522387-1024x1394.jpg 1024w,
          /wp-content/uploads/2026/01/4oclock-e1768496522387-793x1080.jpg 793w" sizes="(max-width: 1067px)
          100vw, 1067px" /></p>
          <p>Our 4 O&#8217;clock Church is one of our family focused groups that takes place on the first
          Sunday of the month during school term time. Its lots of fun an features a mix of different themes
          with crafts and activities as well as some lovely food and drink!</p>
    excerpt: "<p>4 O'Clock Church is a family service with different themes, crafts and activities.</p>"
    title: "4 O'clock Church - Family Service (afternoon)"
    starttime: "16:00:00"
    endtime: "17:00:00"
    skipmonths:
      - 8
    tags:
      - family
      - 4oclock
      - afternoon
      - music
      - singing
      - refreshments
      - freshexpression
    categories:
      - family
    image: 965
  singingangels:
    days:
      - 6
    weeks:
      - 2
    disabled: False
    desc: >
          <h1>Singing Angels</h1>
          <p><img decoding="async" class="aligncenter wp-image-958 size-full"
          src="https://www.stmaryos.org.uk/wp-content/uploads/2026/01/singingangels-e1768496539880.jpg"
          alt="" width="1080" height="1440"
          srcset="https://www.stmaryos.org.uk/wp-content/uploads/2026/01/singingangels-e1768496539880.jpg 1080w,
          https://www.stmaryos.org.uk/wp-content/uploads/2026/01/singingangels-e1768496539880-225x300.jpg 225w,
          https://www.stmaryos.org.uk/wp-content/uploads/2026/01/singingangels-e1768496539880-768x1024.jpg 768w,
          https://www.stmaryos.org.uk/wp-content/uploads/2026/01/singingangels-e1768496539880-1024x1365.jpg 1024w,
          https://www.stmaryos.org.uk/wp-content/uploads/2026/01/singingangels-e1768496539880-810x1080.jpg 810w"
          sizes="(max-width: 1080px) 100vw, 1080px" /></p>
          <p>A multigenerational group for children and adults who love to sing.</p>
          <p>A fun session on the second Sunday of each much including refreshments at no cost.</p>
    excerpt: "<p>Bringing FUN &amp; HAPPINESS through SINGING!</p>"
    title: "Singing Angels (afternoon)"
    starttime: "16:00:00"
    endtime: "17:00:00"
    skipmonths:
      - 8
    tags:
      - family
      - singingangels
      - afternoon
      - music
      - singing
      - refreshments
      - freshexpression
    categories:
      - family
    image: 1127
# Monday
  craftandchat:
    days:
      - 0
    weeks:
    disabled: False
    desc: >
          <h1>Craft and Chat</h1>
          <p>Everyone welcome - held in the Coach House</p>
    excerpt: "<p>Everyone welcome - held in the Coach House</p>"
    title: "Craft and Chat"
    venue: coach-house
    starttime: "14:00:00"
    endtime: "16:00:00"
    skipmonths:
      - 8
    tags:
      - social
      - refreshments
      - craftandchat
    categories:
      - social
      - craftandchat
    image: 1193
# Tuesday
  teaontuesday:
    days:
      - 1
    weeks:
    disabled: False
    desc: >
          <h1>Tea on a Tuesday</h1>
          <p>All are welcome - held in the Coach House</p>
    excerpt: "<p>All are welcome - held in the Coach House</p>"
    title: "Tea on a Tuesday"
    venue: coach-house
    starttime: "14:00:00"
    endtime: "16:00:00"
    skipmonths:
      - 8
    tags:
      - social
      - refreshments
      - teaontuesday
    categories:
      - social
      - teaontuesday
    image: 1179
# Thursday
  thursdaycommunion:
    days:
      - 3
    weeks:
    disabled: False
    desc: "<p>Holy Communion from the Book of Common Prayer.</p>"
    title: "Holy Communion (morning)"
    starttime: "10:30:00"
    endtime: "11:15:00"
    tags:
      - communion
      - bcp
      - service
      - morning
      - worship
    categories:
      - communion
      - worship
    image: 963
# Friday
  youthclub:
    days:
      - 4
    weeks:
    disabled: False
    desc: "<p>Youth Club in the Church Hall</p>"
    excerpt: "<p>Youth Club in the Church Hall</p>"
    title: "Youth Club"
    venue: st-marys-church-hall
    starttime: "18:00:00"
    endtime: "19:00:00"
    skipmonths:
      - 8
    tags:
      - social
      - youthclub
    categories:
      - social
      - youthclub
    image: 1167
  adultchoir:
    days:
      - 4
    disabled: False
    desc: >
          <h1>Adult Choir Rehearsal</h1>
          <p>Our choir normally rehearses on a Friday evening, the Junior Choir start
          rehearsal earlier than the Adult choir and are joined by the Adult Choir.</p>
          <p>Music plays an important part in the life of St Mary's Church, information
          on <a href='/music-at-st-marys/'>joining the choir</a> is available.</p>
    excerpt: "<p>Our adult and junior choirs rehearse during term time on a Friday evening.</p>"
    title: "Adult Choir Rehearsal"
    starttime: "19:30:00"
    endtime: "21:00:00"
    skipmonths:
      - 8
    tags:
      - choir
      - choirrehearsal
      - music
      - singing
    categories:
      - choirrehearsal
    image: 962
  juniorchoir:
    days:
      - 4
    disabled: True
    desc: >
          <h1>Junior Choir Rehearsal</h1>
          <p>Our choir normally rehearses on a Friday evening, the Junior Choir start
          rehearsal earlier than the Adult choir and are joined by the Adult Choir.</p>
          <p>Music plays an important part in the life of St Mary's Church, information
          on <a href='/music-at-st-marys/'>joining the choir</a> is available.</p>
    excerpt: "<p>Our adult and junior choirs rehearse during term time on a Friday evening.</p>"
    title: "Junior Choir Rehearsal"
    starttime: "19:00:00"
    endtime: "20:30:00"
    skipmonths:
      - 8
    tags:
      - choir
      - choirrehearsal
      - music
      - singing
    categories:
      - choirrehearsal
    image: 962
# Saturday
  workwithwardens:
    days:
      - 5
    weeks:
      - 2
    disabled: False
    desc: >
          <h1>Work with the Wardens</h1>
          <p>Work with the Wardens takes place on the second Saturday of each month and brings together the local
          community to help keep the Church and grounds in good condition.</p>
          <p>You could be:</p>
          <ul>
          <li>Weeding the paths</li>
          <li>Clearing leaves</li>
          <li>Planting bulbs</li>
          <li>Dusting the porch</li>
          </ul>
    excerpt: "<p>Help keep the church and grounds in good condition!</p>"
    title: "Work with the Wardens"
    venue: st-marys-church
    starttime: "10:00:00"
    endtime: "12:00:00"
    skipmonths:
      - 8
    tags:
      - social
      - refreshments
      - workwithwardens
    categories:
      - social
      - workwithwardens
    image: 1206
